AllCops:
  Includes:
    - 'Gemfile'
    - 'Rakefile'
    - 'tasks/*.rake'
    - 'bin/t'
    - 't.gemspec'

# Avoid long parameter lists
ParameterLists:
  Max: 3
  CountKeywordArgs: true

# Thor makes it hard to write short classes
ClassLength:
  Enabled: false

LineLength:
  Enabled: false

# Thor makes it hard to write short methods
MethodLength:
  Enabled: false

# Avoid more than `Max` levels of nesting.
BlockNesting:
  Max: 2

CyclomaticComplexity:
  Max: 11 # TODO: Lower to 6

# Align with the style guide.
CollectionMethods:
  PreferredMethods:
    map:      'collect'
    reduce:   'inject'
    find:     'detect'
    find_all: 'select'

# Disable documentation checking until a class needs to be documented once
Documentation:
  Enabled: false

# Enforce Ruby 1.8-compatible hash syntax
HashSyntax:
  EnforcedStyle: hash_rockets

# No spaces inside hash literals
SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Allow dots at the end of lines
DotPosition:
  Enabled: false

# Don't require magic comment at the top of every file
Encoding:
  Enabled: false

# Enforce outdenting of access modifiers (i.e. public, private, protected)
AccessModifierIndentation:
  EnforcedStyle: outdent

EmptyLinesAroundAccessModifier:
  Enabled: true

# Trailing whitespace is required to test output
TrailingWhitespace:
  Enabled: false

# Align ends correctly
EndAlignment:
  AlignWith: variable

# Indentation of when/else
CaseIndentation:
  IndentWhenRelativeTo: end
  IndentOneStep: false

Lambda:
  Enabled: false

RaiseArgs:
  EnforcedStyle: compact

TrailingComma:
  Enabled: false
